template: "Up and running successfully"

dataSource:
  driverClass: com.mysql.cj.jdbc.Driver
  user: root
  password: root
  url: jdbc:mysql://localhost:3306/oms
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate.show_sql: true
    hibernate.format_sql: true
    hibernate.hbm2ddl.auto: update
    hibernate.current_session_context_class: org.hibernate.context.internal.ManagedSessionContext
